# Generated by Django 5.2.8 on 2025-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_bnb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
