# Generated by Django 5.2.8 on 2025-11-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_bnb', '0004_country_alter_propertyimage_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_property', to='air_bnb.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_property', to='air_bnb.country'),
        ),
    ]
