# Generated by Django 5.2.8 on 2025-11-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_bnb', '0005_alter_property_city_alter_property_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
