# Generated by Django 5.2.8 on 2025-11-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_bnb', '0007_alter_property_owner_alter_review_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_name', models.CharField(max_length=150)),
                ('rules_name_en', models.CharField(max_length=150, null=True)),
                ('rules_name_ru', models.CharField(max_length=150, null=True)),
                ('rules_image', models.ImageField(blank=True, null=True, upload_to='rules_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rules',
        ),
        migrations.AlterField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.ManyToManyField(related_name='rules_property', to='air_bnb.rules'),
        ),
    ]
